import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Quiosco Next.js",
  description: "Generated by create next app",
};

const font = Inter({
  subsets: ["latin"],
  weight: ["400", "700", "900"]
})

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${font.className} bg-gray-200`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
